### ISSUE TITLE
Very slow boot

### ISSUE THREAD

**Issue by oliwer** [mcrute/alpine-ec2-ami#39] opened 2019-02-14 21:06 UTC
I have tested alpine-ami-3.9 on several t2.* instances and I have noticed they take several minutes to boot. More precisely, i have to wait at least 3 minutes before OpenSSH starts listening for connections. These logs from a t2.nano confirm this:

```
Feb 14 20:21:24 localhost syslog.info syslogd started: BusyBox v1.29.3
Feb 14 20:21:24 localhost daemon.info init: starting pid 2276, tty '': '/sbin/openrc default'
Feb 14 20:21:26 localhost daemon.info chronyd[2401]: chronyd version 3.4 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP -SCFILTER +SIGND +A
SYNCDNS -SECHASH +IPV6 -DEBUG)
Feb 14 20:21:26 localhost daemon.warn chronyd[2401]: Could not read valid frequency and skew from driftfile /var/lib/chrony/chrony.drift
Feb 14 20:21:30 localhost daemon.info chronyd[2401]: System's initial offset : 0.277395 seconds slow of true (slew)
Feb 14 20:21:36 localhost daemon.info chronyd[2401]: Selected source 169.254.169.123
Feb 14 20:24:48 localhost auth.info sshd[2431]: Server listening on 0.0.0.0 port 22.
Feb 14 20:24:48 localhost auth.info sshd[2431]: Server listening on :: port 22.
```

Notice how sshd starts about 3 minutes after chrony.

I suspected this was due to a lack of entropy during the host keys generation process, and indeed, after I installed haveged the problem was gone.

```
Feb 14 20:47:51 ip-172-31-36-235 daemon.info chronyd[2410]: System's initial offset : 0.096570 seconds slow of true (slew)
Feb 14 20:47:53 ip-172-31-36-235 auth.info sshd[2440]: Server listening on 0.0.0.0 port 22.
```

So I guess it would be a good idea to ship haveged by default, unless you have a better idea?

edit: I just found the corresponding issue on [Redmine](https://bugs.alpinelinux.org/issues/9960). Adding the flag in the kernel's command line would certainly be less invasive, unless you're highly paranoid.

**Comment by tomalok** [comment] 2019-02-15 01:58
Thanks for the link to https://bugs.alpinelinux.org/issues/9960 -- in general, I'd say we wait and see where that leads and then follow Alpine's official decision -- especially when it comes to kernel command line defaults.

FWIW, I've experienced this as well (~2-3m for SSH availability on t3.nano), so on my personal customized Alpine AMIs, I add `haveged` to the boot runlevel, install an `/etc/local.d/99_stop-haveged.start` script, and add `local` to the default runlevel.  With this, I can get it down to ~6s to SSH availability.

At the time, I opted not to include this workaround in the public AMIs, and stick to the bare minimum with as few deviations as possible.  I'm willing to revisit that decision (opinions, @mcrute?)...

**Comment by mcrute** [comment] 2019-02-24 04:30
I'm definitely a fan of keeping the image as minimal as possible but I want to make sure that it provides a good experience for people trying to run Alpine on EC2. AWS has made pretty major improvements in the boot speeds of the latest generation of hardware and it seems a shame to make Alpine users wait an extra 2-3 minutes to be able to ssh into their machine when we can easily ship one more, fairly small, package to drastically improve the siltation. I'd vote in favor of adding haveged to the base image, users can always purge it later if they don't want it around.

**Comment by oliwer** [comment] 2019-02-24 09:25
I did some more research and it seems compiling virtio-rng statically in the kernel allows it to start gathering entropy sooner at boot. That's what CoreOS did and they don't ship haveged or rngd. Could someone test this please?

**Comment by tomalok** [comment] 2019-02-24 19:26
I did some quick non-scientific tests a few days ago on a t3.nano that wasn't doing much of anything (i.e. not adding much entropy based on what it was doing) installed `rng-tools` and ran `cat /dev/random | rngtest -c 1000` a couple times.

With `haveged` running, the test generally completed between 1.4s and 1.6s, with an input channel speed of 14.0 - 14.4 Mbit/s.

With `rngd` running instead (using the RDRAND/RDSEED cpu instruction), completing the test around 2.5s, and an input channel speed of 8 Mbit/s.

With both running, results were roughly averaged between running one or the other.

Without either entropy daemon running, well, I left `rngtest` going for 10 minutes before stopping it, without results.

The same thing happened after I did a `modprobe virtio-rng` -- the module does not automatically add to system entropy on its own, though it did create a `/dev/hwrng` device.  It was not possible to directly use this device in place of `/dev/random` for testing, but it's supposed to be possible to use it as a source for `rngd`...  Unfortunately, it did not recognize the device as something it could use as a source (`-r /dev/hwrng`), and fell back to using RDRAND/RDSEED.

Spun up a CoreOS Container Linux 2051.0.0 instance on another t3.nano.  While SSH is quickly available, `rngtest` hangs the same way as Alpine without `haveged` or `rngd` running, so something else seems to be going on.

Looked at the differences between the kernel configs, and one thing that jumps out at me is that CoreOS has CONFIG_HW_RANDOM_TPM enabled...

> This setting exposes the TPM's Random Number Generator as a hwrng device. This allows the kernel to collect randomness from the TPM at boot, and provides the TPM randomines in /dev/hwrng.

...that's _probably_ what we're missing.  I'll see about getting that into the configs for alpinelinux/aports/main/linux-vanilla (where all the kernel flavor configs live) and perhaps we can get a real fix in "edge".  Taking a deeper look into the kernel configs has been on my TODO list...

In the meantime, I've got a patch to add `haveged` to the boot runlevel.  I'll get that in place today/tomorrow and build a "3.9.0-1" set of images (also including the fix for #40).

**Comment by tomalok** [comment] 2019-02-26 02:10
The "3.9.0-1" AMIs (or codebase if you're rolling with your own `variables.yaml` config) should address this issue in the short term.

**Comment by ncopa** [comment] 2019-02-26 18:56
Apparently alpine already have `CONFIG_HW_RANDOM_TPM=y`
I notice that fedora and coreos has `CONFIG_HW_RANDOM_VIRTIO=y`. Maybe that helps?

https://github.com/coreos/coreos-overlay/pull/3231/commits/fa4f2f4db6af68c59d018cf38c10d26073d50771

**Comment by tomalok** [comment] 2019-02-27 16:55
While flddling around with `config-virt.x86` kernel settings last night, I got it down to about 53s to get to `random: crng-init done` on a reboot (haven't tried it from an initial instantiation yet).

Took a look at what else coreos might be doing -- turns out there's a `systemd-random-seed.service` that appears to be running right before it achieves `random: crng-init done` at around 6.7s (also a reboot, since that instance decided to update itself to 2065.0.0).  This may be similar (or go beyond) what OpenRC's `urandom` script is meant to do.

I'll try to test initial boot times tonight.

**Comment by tomalok** [comment] 2019-03-02 22:31
Fiddling with configs individually or in small groups was getting me nowhere, so I built a linux-virt kernel using the CoreOS config with as few modifications as possible (primarily signed modules)...

Booting with the CoreOSy kernel...  had no positive effect, in fact it was worse.  139.57s to get to `random: crng-init done`.  The fix isn't in the kernel configs.

**Comment by HRio** [comment] 2019-04-22 21:07
This was committed today to alpine v3.9: https://github.com/alpinelinux/aports/commit/265a653bad851898a245bcdc5cb6a8d2143b4bb3

if you add `haveged` and have it start in runlevel boot `rc-update add haveged boot` it will start right after `networking` in the `boot` runlevel.

However if the emulated CPU has `rdrand` in cpu flags, `rngd` from the package `rng-tools` is preferred (`rc-update add rngd boot`).

As `sshd` starts in runlevel `default` you will have `haveged` or `rngd` running way before that.

**Comment by tomalok** [comment] 2019-04-22 23:52
Thanks for the update @HRio, I'll take another look at `rngd`, as I believe that (at least) EC2 instances (well, x86_64 arch at least) have `rdrand` enabled -- there may be some additional linux-virt config work to be done to better support it.

**Comment by HRio** [comment] 2019-04-23 15:49
sshd after entropy fix now in v3.9 https://github.com/alpinelinux/aports/commit/a0125e7de015ab8a1fdf63b9217ce33861b82e1c

**Comment by tomalok** [comment] 2019-04-30 05:36
It also appears that `CONFIG_RANDOM_TRUST_CPU` has been reenabled in main/linux-vanila...

https://github.com/alpinelinux/aports/commit/e67c2f8bcb163695a5917e059a2c7ba46726ee89

...with a link explaining why it's enabled in Ubuntu.

**Comment by ncopa** [comment] 2019-04-30 09:02
i will try backport the `CONFIG_RANDOM_TRUST_CPU` change to `3.9-stable` branch so it gets in cluded with `3.9.4`

**Closed** 2019-07-05 19:51 UTC

**Comment by lAnubisl** [comment] 2019-08-19 20:11
alpine-standard-3.10.1-x86
the issue is still here

**Comment by tomalok** [comment] 2019-08-19 21:51
Could you include an example launch profile that demonstrates what you're seeing, as well as dmesg output from the instance, so that we can investigate the issue?  FWIW, I've launched numerous instances with recent AMIs, and haven't seen a recurrance.

Thanks

iSent from my iPad

**Comment by tomalok** [comment] 2019-08-20 00:13
@lAnubisl, I instantiated a t3.nano from the stock `alpine-ami-3.10.1-x86_64-r1` AMI, and `dmesg` reports...
```
...
[    0.905835] random: crng done (trusting CPU's manufacturer)
...
```
Which is *MUCH* speedier than the 2-3m that it used to take with the 3.9 kernel config change, and still considerably faster than the `haveged` solution we temporarily used (6s) in the interim.

**Comment by lAnubisl** [comment] 2019-08-20 08:48
@tomalok Well. I just realized that this topic relates to ec2-ami only. My issue is related to Alpine installed on my hardware. If you still can do something with this then let me know please.
